// Command notices writes THIRD-PARTY-NOTICES.md: every component compiled into the release
// executables, with its full license text, taken from the module graph and the module cache.
//
// Usage: go run ./scripts/notices [-out THIRD-PARTY-NOTICES.md]
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// target is one release executable and the platform it is built for.
type target struct {
	file, goos, goarch string
}

var targets = []target{
	{"ZweTag.exe", "windows", "amd64"},
	{"zwetag-linux-amd64", "linux", "amd64"},
	{"zwetag-darwin-arm64", "darwin", "arm64"},
	{"zwetag-darwin-amd64", "darwin", "amd64"},
}

type pkg struct {
	ImportPath string
	Standard   bool
	Module     *struct {
		Path    string
		Version string
		Dir     string
		Main    bool
	}
}

type component struct {
	name, version, license, text string
	in                           []string
}

func main() {
	out := flag.String("out", "THIRD-PARTY-NOTICES.md", "file to write")
	flag.Parse()

	byName := map[string]*component{}
	add := func(name, version, licenseFile, file string) {
		c := byName[name]
		if c == nil {
			text, err := os.ReadFile(licenseFile)
			if err != nil {
				die(fmt.Errorf("license of %s: %w", name, err))
			}
			c = &component{name: name, version: version, license: identify(string(text)), text: strings.TrimSpace(string(text))}
			byName[name] = c
		}
		for _, f := range c.in {
			if f == file {
				return
			}
		}
		c.in = append(c.in, file)
	}

	goroot := strings.TrimSpace(run(nil, "go", "env", "GOROOT"))
	for _, t := range targets {
		env := []string{"GOOS=" + t.goos, "GOARCH=" + t.goarch, "CGO_ENABLED=0"}
		dec := json.NewDecoder(strings.NewReader(run(env, "go", "list", "-deps", "-json", "./cmd/zwetag")))
		for {
			var p pkg
			if err := dec.Decode(&p); err == io.EOF {
				break
			} else if err != nil {
				die(err)
			}
			switch {
			case p.Standard:
				add("Go standard library", "the Go release used for the build", filepath.Join(goroot, "LICENSE"), t.file)
			case p.Module != nil && !p.Module.Main:
				add(p.Module.Path, p.Module.Version, licenseFile(p.Module.Dir), t.file)
				if p.ImportPath == "github.com/jchv/go-webview2/webviewloader" {
					add("Microsoft Edge WebView2 loader (WebView2Loader.dll, embedded by go-webview2)",
						"from the WebView2 SDK in "+p.Module.Path+" "+p.Module.Version,
						filepath.Join(p.Module.Dir, "webviewloader", "sdk", "LICENSE.txt"), t.file)
				}
			}
		}
	}

	list := make([]*component, 0, len(byName))
	for _, c := range byName {
		list = append(list, c)
	}
	sort.Slice(list, func(i, j int) bool {
		if (list[i].name == "Go standard library") != (list[j].name == "Go standard library") {
			return list[i].name == "Go standard library"
		}
		return list[i].name < list[j].name
	})

	var b bytes.Buffer
	b.WriteString("# Third-party notices\n\n")
	b.WriteString("The ZweTag executables contain the components below in compiled form. Each keeps its own\n")
	b.WriteString("license; the full texts follow. ZweTag itself is licensed under the Apache License 2.0\n")
	b.WriteString("(see LICENSE). The interface in `web/` uses no third-party code.\n\n")
	b.WriteString("This file is generated by `go run ./scripts/notices`. Do not edit it by hand.\n\n")
	b.WriteString("| Component | Version | License | Included in |\n|---|---|---|---|\n")
	for _, c := range list {
		in := strings.Join(c.in, ", ")
		if len(c.in) == len(targets) {
			in = "all executables"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", c.name, c.version, c.license, in)
	}
	for _, c := range list {
		fmt.Fprintf(&b, "\n## %s\n\n```text\n%s\n```\n", c.name, c.text)
	}
	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		die(err)
	}
	fmt.Printf("wrote %s (%d components)\n", *out, len(list))
}

func licenseFile(dir string) string {
	for _, name := range []string{"LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING"} {
		p := filepath.Join(dir, name)
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	die(fmt.Errorf("no license file in %s", dir))
	return ""
}

// identify names the license of a text by its operative sentences.
func identify(text string) string {
	t := strings.Join(strings.Fields(text), " ")
	switch {
	case strings.Contains(t, "Permission is hereby granted, free of charge"):
		return "MIT"
	case strings.Contains(t, "Permission to use, copy, modify, and/or distribute this software"):
		return "ISC"
	case strings.Contains(t, "Redistribution and use in source and binary forms") &&
		(strings.Contains(t, "Neither the name") || strings.Contains(t, "may not be used to endorse or promote")):
		return "BSD-3-Clause"
	}
	die(fmt.Errorf("unknown license text starting %q", t[:60]))
	return ""
}

func run(env []string, name string, args ...string) string {
	cmd := exec.Command(name, args...)
	cmd.Env = append(os.Environ(), env...)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		die(fmt.Errorf("%s %s: %w", name, strings.Join(args, " "), err))
	}
	return string(out)
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "notices:", err)
	os.Exit(1)
}
